In [1]:
import numpy as np

In [2]:
a = np.array(np.random.randint(2, 100, 27))
a

array([48, 29, 40, 83, 15, 23, 95, 96, 40, 43,  8, 10, 65, 23,  7,  2, 62,
       49, 26, 85, 60, 66, 51, 26, 44,  4, 46])

In [3]:
type(a)

numpy.ndarray

In [4]:
a.ndim

1

In [5]:
a.shape

(27,)

In [6]:
a.size

27

In [7]:
a.dtype

dtype('int32')

In [8]:
# 32/8 = 4 so returns 4
a.itemsize

4

## String operations using numpy

In [9]:
d = np.array(["hello", "World", "programmers"])
e = np.array([" all", " welcome", " python"])

In [10]:
np.char.add(d, e)

array(['hello all', 'World welcome', 'programmers python'], dtype='<U19')

In [11]:
# np.char.replace(con_d_e[0], "hello", "hii")

In [12]:
np.char.upper(d)

array(['HELLO', 'WORLD', 'PROGRAMMERS'], dtype='<U11')

In [13]:
np.char.lower(d)

array(['hello', 'world', 'programmers'], dtype='<U11')

In [14]:
"_".join([str(i) for i in d])

'hello_World_programmers'

## Functions in numpy

In [15]:
# to change the a use np.resize(a,(3,3))
# b = a.reshape(3, 3, 3)
b = np.reshape(a, (3, 3, 3))
b

array([[[48, 29, 40],
        [83, 15, 23],
        [95, 96, 40]],

       [[43,  8, 10],
        [65, 23,  7],
        [ 2, 62, 49]],

       [[26, 85, 60],
        [66, 51, 26],
        [44,  4, 46]]])

In [16]:
np.arange(20, 30, 2)

array([20, 22, 24, 26, 28])

In [17]:
np.random.rand(1)

array([0.72836301])

In [18]:
np.random.random()

0.5668184842997962

In [19]:
np.random.randint(1, 50, 2)

array([28, 44])

In [20]:
# use seed(1) for getting same number
for i in range(5):
    np.random.seed(1)
    print(np.random.randint(1, 50))

38
38
38
38
38


In [21]:
# Create a 2D NumPy array 'x'
x = np.array([[1, 3, 5], [11, 35, 56]])
print("\nFlattened arrays:")

# Flatten the array 'x' using Fortran (column-major) order
y = np.ravel(x, order="F")
print("Fortran (F) order:", y)

# Flatten the array 'x' using C (row-major) order
z = np.ravel(x, order="C")
print("C order:", z)

# Flatten the array 'x' using default (auto) order (row-major in this case)
p = np.ravel(x, order="A")
print("Default (auto) order:", p)

# Flatten the array 'x' using keep (preserve) order
q = np.ravel(x, order="K")
print("Keep (preserve) order:", q)


Flattened arrays:
Fortran (F) order: [ 1 11  3 35  5 56]
C order: [ 1  3  5 11 35 56]
Default (auto) order: [ 1  3  5 11 35 56]
Keep (preserve) order: [ 1  3  5 11 35 56]


In [22]:
np.zeros(2)

array([0., 0.])

In [23]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [24]:
np.ones(2)

array([1., 1.])

In [25]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [26]:
np.arange(1, 50)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [27]:
np.arange(1, 50, 5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [28]:
np.linspace(10, 20, 5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [29]:
x = np.arange(1, 5)
y = np.arange(20, 25)
np.hstack((x, y))

array([ 1,  2,  3,  4, 20, 21, 22, 23, 24])

## Arithemrtic Operations using numpy

In [30]:
a = np.array([[1, 2, 1], [2, 2, 3]])
a

array([[1, 2, 1],
       [2, 2, 3]])

In [31]:
b = np.array([3, 4, 5])
b

array([3, 4, 5])

In [32]:
np.add(a, b)

array([[4, 6, 6],
       [5, 6, 8]])

In [33]:
np.subtract(b, a)

array([[2, 2, 4],
       [1, 2, 2]])

In [34]:
np.multiply(a, b)

array([[ 3,  8,  5],
       [ 6,  8, 15]])

In [35]:
np.divide(a, b)

array([[0.33333333, 0.5       , 0.2       ],
       [0.66666667, 0.5       , 0.6       ]])

In [36]:
np.power(a, b)

array([[  1,  16,   1],
       [  8,  16, 243]])

## Conditional operations using numpy

In [37]:
x = np.array([x for x in range(11)])
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
np.where(x % 2 == 0, "Even", "Odd")

array(['Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even',
       'Odd', 'Even'], dtype='<U4')

In [39]:
conditionList = [x < 5, x > 5]
choiceList = [x**3, x**2]

In [40]:
np.select(conditionList, choiceList, default=0)

array([  0,   1,   8,  27,  64,   0,  36,  49,  64,  81, 100])

## Statistics functions in numpy

In [41]:
arr = np.array([[4, 2, 3], [10, 2, 0], [5, 8, 24]])
arr

array([[ 4,  2,  3],
       [10,  2,  0],
       [ 5,  8, 24]])

In [42]:
np.min(arr, axis=0)

array([4, 2, 0])

In [43]:
np.amin(arr, axis=1)

array([2, 0, 5])

In [44]:
np.max(arr)

24

In [45]:
np.amax(arr, axis=0)

array([10,  8, 24])

In [46]:
np.amax(arr, axis=1)

array([ 4, 10, 24])

In [47]:
np.mean(arr)

6.444444444444445

In [48]:
np.median(arr)

4.0

In [49]:
np.std(arr)

6.865551869233515

In [50]:
np.var(arr)

47.13580246913581

In [51]:
percentile_value = 50
np.percentile(arr, percentile_value)

4.0

In [52]:
deg = np.array([0, 30, 45, 60, 90])
deg

array([ 0, 30, 45, 60, 90])

In [53]:
radians = np.deg2rad(deg)
radians

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [54]:
deg * np.pi / 180

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [55]:
np.sin(deg * np.pi / 180)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [56]:
np.sin(radians)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [57]:
np.cos(radians)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [58]:
np.tan(radians)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [59]:
np.tan(deg)

array([ 0.        , -6.4053312 ,  1.61977519,  0.32004039, -1.99520041])

In [60]:
np.arcsin(radians)

C:\Users\rakes\AppData\Local\Temp\ipykernel_12336\4042167314.py:1: RuntimeWarning: invalid value encountered in arcsin
  np.arcsin(radians)


array([0.        , 0.55106958, 0.90333911,        nan,        nan])

In [61]:
np.arccos(radians)

C:\Users\rakes\AppData\Local\Temp\ipykernel_12336\194661201.py:1: RuntimeWarning: invalid value encountered in arccos
  np.arccos(radians)


array([1.57079633, 1.01972674, 0.66745722,        nan,        nan])

In [62]:
np.arctan(radians)

array([0.        , 0.48234791, 0.66577375, 0.80844879, 1.00388482])

In [63]:
a = np.random.rand(1, 5)
a

array([[0.99718481, 0.93255736, 0.12812445, 0.99904052, 0.23608898]])

In [64]:
np.floor(a)

array([[0., 0., 0., 0., 0.]])

In [65]:
np.ceil(a)

array([[1., 1., 1., 1., 1.]])

## Indexing and slicing 

### 1D array

In [66]:
arr = np.arange(1, 10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
arr[5]

6

In [68]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [69]:
arr[3:-1]

array([4, 5, 6, 7, 8])

In [70]:
arr[-5:-1]

array([5, 6, 7, 8])

### 2D array

In [71]:
arr = np.arange(1, 26).reshape(5, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [72]:
arr[0][2]

3

In [73]:
arr[0, 2]

3

In [74]:
arr[
    -2:,
]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [75]:
arr[
    2:5,
]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [76]:
arr[:, 2:5]

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20],
       [23, 24, 25]])

In [77]:
arr[2:5, 3:5]

array([[14, 15],
       [19, 20],
       [24, 25]])